const zones=[{city:'Singapore',zone:'Asia/Singapore'},{city:'Gothenburg',zone:'Europe/Stockholm'},{city:'San Francisco',zone:'America/Los_Angeles'}];
const tasks=[['Finalize KHiO portfolio alignment','Application · 45 min'],['Methodology interview practice','Research · 30 min'],['Review new fellowship matches','Opportunities · 20 min'],['Extract notes from today’s reading','Reading · 25 min'],['Update application evidence list','Archive · 15 min']];
let completed=new Set(JSON.parse(localStorage.getItem('pid-tasks')||'[3]'));
const fmt=(date,zone)=>new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:zone}).format(date);
function updateClocks(){const now=new Date();document.querySelector('#local-time').textContent=fmt(now,zones[0].zone);document.querySelectorAll('[data-zone]').forEach(el=>el.textContent=fmt(now,el.dataset.zone));}
function renderZones(){document.querySelector('#zone-list').innerHTML=zones.map((z,i)=>`<label class="zone-row"><input type="checkbox" checked data-zone-toggle="${i}"><span>${z.city}</span><time data-zone="${z.zone}">--:--</time></label>`).join('');updateClocks();document.querySelectorAll('[data-zone-toggle]').forEach(box=>box.addEventListener('change',e=>e.target.closest('.zone-row').classList.toggle('off',!e.target.checked)));}
function renderCalendar(){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),today=now.getDate();const name=new Intl.DateTimeFormat('en',{month:'long'}).format(now);document.querySelector('#calendar-title').innerHTML=`${name} <span>${year}</span>`;const start=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),grid=document.querySelector('#calendar-grid');grid.innerHTML='';for(let i=0;i<42;i++){const day=i-start+1,b=document.createElement('button');b.type='button';if(day<1||day>days)b.className='blank';else{b.textContent=day;if(day>=today-2&&day<=today+3)b.classList.add('cycle');if(day===today)b.classList.add('today');b.setAttribute('aria-label',`${name} ${day}${day===today?', today':''}`)}grid.appendChild(b);}}
function renderTasks(){const list=document.querySelector('#task-list');list.innerHTML=tasks.map((t,i)=>`<label class="task-row ${completed.has(i)?'is-done':''}"><input type="checkbox" data-task="${i}" ${completed.has(i)?'checked':''}><span class="task-copy"><strong>${t[0]}</strong><small>${t[1]}</small></span></label>`).join('');document.querySelector('#remaining-count').textContent=`${tasks.length-completed.size} remaining`;list.querySelectorAll('[data-task]').forEach(box=>box.addEventListener('change',e=>{const id=Number(e.target.dataset.task);e.target.checked?completed.add(id):completed.delete(id);localStorage.setItem('pid-tasks',JSON.stringify([...completed]));renderTasks();}));}
const timeButton=document.querySelector('#time-open'),world=document.querySelector('#world-popover');timeButton.addEventListener('click',()=>{world.hidden=!world.hidden;timeButton.setAttribute('aria-expanded',String(!world.hidden));});
const overlay=document.querySelector('#search-overlay'),searchInput=document.querySelector('#search-input'),results=document.querySelector('#search-results');
function openSearch(){overlay.hidden=false;setTimeout(()=>searchInput.focus(),0)}function closeSearch(){overlay.hidden=true;searchInput.value='';results.innerHTML='<p>Type a keyword to search across your dashboard.</p>'}
document.querySelector('#search-open').addEventListener('click',openSearch);document.querySelector('#search-close').addEventListener('click',closeSearch);overlay.addEventListener('click',e=>{if(e.target===overlay)closeSearch()});
searchInput.addEventListener('input',()=>{const q=searchInput.value.trim().toLowerCase();if(!q){results.innerHTML='<p>Type a keyword to search across your dashboard.</p>';return}const items=[...document.querySelectorAll('[data-search]')].filter(el=>el.dataset.search.includes(q)||el.textContent.toLowerCase().includes(q));results.innerHTML=items.length?items.map((el,i)=>`<button type="button"><span>0${i+1}</span>${el.querySelector('strong').textContent}<b>→</b></button>`).join(''):'<p>No keyword matches found.</p>';});
const capture=document.querySelector('#capture-popover');document.querySelector('#capture-open').addEventListener('click',()=>{capture.hidden=false;capture.querySelector('textarea').focus()});document.querySelector('#capture-close').addEventListener('click',()=>capture.hidden=true);document.querySelector('#capture-save').addEventListener('click',()=>{capture.querySelector('textarea').value='';capture.hidden=true});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){closeSearch();capture.hidden=true;world.hidden=true}});
renderZones();renderCalendar();renderTasks();updateClocks();setInterval(updateClocks,1000);
